I have slightly improved smooth colors that look better and are more responsive on mobile devices. Also add a search box
MelSumner/a11y-automation pull request #47
Opened 2020-10-22 12:57 UTC by tranjenny

I have slightly improved smooth colors that look better and are more responsive on mobile devices. Also add a search box

2020-10-22 14:17 UTC, MelSumner commented on app/index.html
> +    <title>A11yAutomation999</title>
```suggestion
    <title>A11yAutomation</title>
```

2020-10-22 14:18 UTC, MelSumner commented on app/styles/layout/_status.scss
> +@media only screen and (max-width:400px) {
Since the styles are "mobile-first", these can be added as the base styles, then a media query added for larger breakpoints.

2020-10-22 14:21 UTC, MelSumner commented on app/styles/_variables.scss
> +$black: #686469;
This color results in a non-conformant color contrast: 

"Element has insufficient color contrast of 2.49 (foreground color: #686469, background color: #a9aaab, font size: 13.5pt (18px), font weight: bold). Expected contrast ratio of 4.5:1"

If we can find a "less black" black that will pass color contrast checks, that would be fine to change.

2020-10-22 14:24 UTC, MelSumner commented on app/templates/application.hbs
> +    <p>{{input type="text" class="search" placeholder="Search" value=search action="queryPost"}}</p>
All form elements require an associated `<label>` element. Do you know if this addon accepts the `aria-label` attribute? If we add `aria-label="search potential failures"` to this input, that would suffice. 👍

2020-10-22 14:25 UTC, MelSumner requested changes
Thank you for your PR! There are a few things that need to be slightly tweaked but after that I would be delighted to merge this PR. 👍

2020-10-22 15:07 UTC, tranjenny commented
oh really sorry, i forgot to just fix the markers for distinction, i'm stupid for not checking carefully

2020-10-22 15:09 UTC, tranjenny commented
Thank you for the feedback, I'll need to do it again

2020-11-02 15:52 UTC, MelSumner commented
@tranjenny would you like to keep this PR open and work on it, or would you like me to close it and have you open another PR?

2020-11-05 20:54 UTC, closed without merging